### ISSUE TITLE
About this plugin

### ISSUE THREAD

**Issue by IamFonky** [runreflect/webpack-react-component-name#23]
Sorry to write that here but I had no other way to communicate with you.
I came across some bugs when trying to use your plugin in production.
If you use external libraries like react-select and you build them in production mode (webpack) all the external components will be renamed.
If you're using this plugin for the same reason than me, which is for client testing (cypress in my case), external component names will be shown in development mode but not in production. Your tests might fail in the production pipeline.
The thing that is renaming components in webpack is TerserPlugin and it is added by default  in production mode [see TerserPlugin usage line 1143](https://github.com/webpack/webpack/blob/main/lib/config/defaults.js)

To avoid this problem I overrode the TerserPlugin usage by adding an optimization in webpack config
``` js
module.exports = {
...
  optimization: {
    minimizer: [
      compiler => {
        const TerserPlugin = require('terser-webpack-plugin');
        new TerserPlugin({
          terserOptions: {
            mangle: {
              keep_classnames: true,
              keep_fnames: true,
            },
            compress: {
              passes: 2,
            },
          },
        }).apply(compiler);
      },
    ],
  },
...
}
```
and it worked.

I removed your plugin and the names are still here so I think this trick does the exact same job as your plugin :cry: 

If you're using wegas-dev-server  and to be sure you that the output is the same than in production, you can add a script to your package.json that force in production mode
```json
{
  ...
  "scripts": {
    ...
    "build": "webpack --mode production",
    "start": "webpack serve --hot --mode development",
    "preprod": "webpack serve --hot --mode production",
    ...
  },
  ...
}
```

**Comment by IamFonky** [comment]
After doing some test, i see that some of the components declared as const MyComponent = ()=>{...} are shown as Anonymous.
You can ether use your plugin to get the names back or add MyComponent.displayName = "MyComponent"; after the component declaration.

**Comment by tmcneal** [comment]
Hi @IamFonky, thanks for opening this issue! You are correct that if you modify the terser plugin to not minify classnames and function names, then you will be able to see React components in e.g. React DevTools. However, this comes at the cost of an increased bundle size, since all functions and classes passing through TerserPlugin will not be minified. I believe that most orgs would consider this a non-starter due to the performance impact.

Our plugin works by appending a `displayName` property to each component definition. This only adds a few KB to your bundle size and allows you to keep all classes and functions minified.

Regarding your second comment, would you be able to provide an example file containing a component that we are not detecting? I can then confirm the repro and cut a fix.

**Comment by IamFonky** [comment]
Thanks for your answer. You're right, my hack make a 9% size increase for my bundle.
I'm trying to make a example in codesandbox to show you when does the plugin fail but I can't reproduce the problem with external component (react-select) for the moment.
I'll update this issue as soon as I find a good example.

**Comment by IamFonky** [comment]
Actually, this problem does not need any reproduction. The only thing that is preventing me from using your plugin is the fact that it ignores the node_modules files.
I'll send you a PR in a minute to take an option into and do the trick.

**Comment by tmcneal** [comment]
Awesome! I'll happily merge that.
